### ISSUE TITLE
debugging under eclipse (Windows Server 2012 R2) fails after importing maven project

### ISSUE THREAD

**Issue by datasmithtech** [gazbert/bxbot#49] opened 2017-02-25 13:36 UTC
Error creating bean with name 'tradingEngine' defined in file [C:\TradingBots\bxbot\bxbot-core\target\classes\com\gazbert\bxbot\core\engine\TradingEngine.class]: Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'emailAlerter' defined in file [C:\TradingBots\bxbot\bxbot-core\target\classes\com\gazbert\bxbot\core\mail\EmailAlerter.class]: Bean instantiation via constructor failed; 

nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.gazbert.bxbot.core.mail.EmailAlerter]: Constructor threw exception; nested exception is java.lang.IllegalStateException: 

Failed to find or read [config/email-alerts.xml] config; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'emailAlerter' defined in file [C:\TradingBots\bxbot\bxbot-core\target\classes\com\gazbert\bxbot\core\mail\EmailAlerter.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.gazbert.bxbot.core.mail.EmailAlerter]: Constructor threw exception; nested exception is java.lang.IllegalStateException: 
Failed to find or read [config/email-alerts.xml] config

**Comment by gazbert** [comment] 2017-02-25 19:08
Not sure about this one. I've just spun up the bot in IntelliJ on Windows - see attached screenshot.

Are you starting 
![bxbot-windows-intellij-spring-booted](https://cloud.githubusercontent.com/assets/6501814/23333998/d8494aea-fb8d-11e6-83b7-a8b6de8aa681.png)
the app from the main Boot app - BXBot.java - in Eclipse?

**Comment by gazbert** [comment] 2017-03-11 22:36
Closing - can't reproduce.

**Closed by gazbert** 2017-03-11 22:36 UTC
