### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [gazbert/bxbot#111] opened 2019-07-02 17:23 UTC
Hi
The following lines have cryptographic API misuses. <br> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/ItBitExchangeAdapter.java: Line number => 1075: API name => SecretKeySpec:<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/GdaxExchangeAdapter.java: Line number => 898: API name => SecretKeySpec:<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/CryptopiaExchangeAdapter.java: Line number => 742: API name => Mac:Operation on object of type javax.crypto.Mac object not completed. Expected call to update, doFinal<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/BitstampExchangeAdapter.java: Line number => 828: API name => SecretKeySpec:<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/GdaxExchangeAdapter.java: Line number => 899: API name => Mac:Operation on object of type javax.crypto.Mac object not completed. Expected call to update, doFinal<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/BitstampExchangeAdapter.java: Line number => 829: API name => Mac:Operation on object of type javax.crypto.Mac object not completed. Expected call to update, doFinal<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/BitfinexExchangeAdapter.java: Line number => 989: API name => Mac:Operation on object of type javax.crypto.Mac object not completed. Expected call to update, doFinal<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/GdaxExchangeAdapter.java: Line number => 898: API name => SecretKeySpec:<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/BitfinexExchangeAdapter.java: Line number => 988: API name => SecretKeySpec:<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/BitfinexExchangeAdapter.java: Line number => 988: API name => SecretKeySpec:<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/BitstampExchangeAdapter.java: Line number => 828: API name => SecretKeySpec:<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/CryptopiaExchangeAdapter.java: Line number => 745: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/CryptopiaExchangeAdapter.java: Line number => 741: API name => SecretKeySpec:<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/KrakenExchangeAdapter.java: Line number => 1244: API name => SecretKeySpec:<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/GeminiExchangeAdapter.java: Line number => 816: API name => SecretKeySpec:<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/ItBitExchangeAdapter.java: Line number => 1076: API name => Mac:Operation on object of type javax.crypto.Mac object not completed. Expected call to update, doFinal<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/CryptopiaExchangeAdapter.java: Line number => 741: API name => SecretKeySpec:<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/GeminiExchangeAdapter.java: Line number => 816: API name => SecretKeySpec:<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/KrakenExchangeAdapter.java: Line number => 1244: API name => SecretKeySpec:<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/OkCoinExchangeAdapter.java: Line number => 909: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/KrakenExchangeAdapter.java: Line number => 1245: API name => Mac:Operation on object of type javax.crypto.Mac object not completed. Expected call to update, doFinal<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/ItBitExchangeAdapter.java: Line number => 1075: API name => SecretKeySpec:<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/GeminiExchangeAdapter.java: Line number => 817: API name => Mac:Operation on object of type javax.crypto.Mac object not completed. Expected call to update, doFinal<BR> File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/HuobiExchangeAdapter.java: Line number => 1093: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR>

**Comment by gazbert** [comment] 2019-07-02 20:19
Looks like a bot... and not a very helpful one. The code it's referenced is old too - Crytpopia and Huobo exchanges have gone.

`API name => SecretKeySpec ` 

- ?!! No idea what the problem is here.

`File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/GdaxExchangeAdapter.java: Line number => 899: API name => Mac:Operation on object of type javax.crypto.Mac object not completed. Expected call to update, doFinal` 

- yes it is! Likewise for all the other adapters.

`File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/OkCoinExchangeAdapter.java: Line number => 909: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update
`
- yes it is. Likewise for all the other adapters.

`File name => bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/CryptopiaExchangeAdapter.java: Line number => 745: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}`

- fair point, it is a weak hash, but this is what the exchange mandated - the adapter has been removed since the exchange was liquidated. 

Closing.

**Closed by gazbert** 2019-07-02 20:19 UTC
